### ISSUE TITLE
installing with a different language renders custom blocks unusable

### ISSUE THREAD

**Issue by carlosmirandalevy** [markaspot/mark-a-spot#47] opened 2017-03-11 17:27 UTC
If a language other than English is chosen during installation of the distribution, the custom blocks (_Welcome!_, _Add block_ and _mas custom_) are generated empty and for some reason even when edited, they do not show up on the front page. 

They are created by the install script and show up on the blocks management pages, but end up empty and even when edited, they render empty (or don't render) on the frontpage.

I tried this several times on clean install with Spanish or French. When the default language (English) is used, the custom blocks are created by the installation script and display on the frontpage.

![screen shot 2017-03-11 at 5 40 01 pm](https://cloud.githubusercontent.com/assets/277457/23825334/f7c3fda2-0687-11e7-8a2d-cf2b940b609f.png)

![screen shot 2017-03-11 at 6 20 40 pm](https://cloud.githubusercontent.com/assets/277457/23825342/2908d964-0688-11e7-997f-144b17d75f54.png)

![screen shot 2017-03-11 at 6 26 37 pm](https://cloud.githubusercontent.com/assets/277457/23825353/59f186b6-0688-11e7-8a2b-a8241368db76.png)

**Comment by markaspot** [comment] 2017-03-12 04:13
I think this has to be by design, as default content needs at least one language being applied. The HAL/JSON content needs a language property that is english by default. Maybe I am wrong with that. Anyway, you can have editable blocks as block_content entities (see Issue [https://github.com/markaspot/mark-a-spot/issues/42](url) or have them hard-coded in every language.

**Comment by markaspot** [comment] 2018-02-06 10:34
Closing this.

**Closed by markaspot** 2018-02-06 10:34 UTC
